# Generated by Django 3.2 on 2021-04-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20210429_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='befollowed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='befollowedtext',
            field=models.TextField(blank=True, default='initial', null=True),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='follow',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='followtext',
            field=models.TextField(blank=True, default='initial', null=True),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='readtext',
            field=models.TextField(blank=True, default='initial', null=True),
        ),
    ]
