# Generated by Django 3.2 on 2021-04-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_auto_20210430_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('follow', models.IntegerField(blank=True, default=0, null=True)),
                ('followtext', models.TextField(blank=True, default='initial', null=True)),
                ('befollowed', models.IntegerField(blank=True, default=0, null=True)),
                ('befollowedtext', models.TextField(blank=True, default='initial', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='befollowed',
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='befollowedtext',
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='followtext',
        ),
    ]
