# Generated by Django 3.2 on 2021-05-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_auto_20210430_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('one_thing', models.TextField()),
                ('header_image', models.ImageField(upload_to='')),
                ('follow_number', models.IntegerField(blank=True, default=0, null=True)),
                ('follow_text', models.TextField(blank=True, default='initial', null=True)),
                ('befollowed_number', models.IntegerField(blank=True, default=0, null=True)),
                ('befollowed_text', models.TextField(blank=True, default='initial', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FollowModel',
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='read',
        ),
    ]
