# Generated by Django 3.2 on 2021-05-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_auto_20210501_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='sns_image',
            field=models.ImageField(blank=True, default=0, null=True, upload_to=''),
        ),
    ]
