# Generated by Django 3.2 on 2021-05-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0007_auto_20210503_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='befollowed_text',
            field=models.TextField(blank=True, default='initial', null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='follow_text',
            field=models.TextField(blank=True, default='initial', null=True),
        ),
    ]
