# Generated by Django 3.2.7 on 2021-09-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0009_auto_20210908_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='sns_image',
        ),
    ]
