# Generated by Django 3.2 on 2021-09-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0010_remove_boardmodel_sns_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='article_urls',
            field=models.URLField(blank=True, default=0, null=True),
        ),
    ]
